spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: auth_user
    password: auth_password

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/