server:
  port: 8766

spring:
  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

info:
  app:
    name: Auth Service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
