server:
  port: 8763

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/cart_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

info:
  app:
    name: Cart Service
