server:
  port: 8763

spring:

  datasource:
    url: ${CART_DB_URL}
    username: ${CART_DB_USER}
    password: ${CART_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

info:
  app:
    name: Cart Service
    version: 1.0.0
