spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/cart_db
    username: cart_user
    password: cart_password

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/