server:
  port: 8761

spring:

  security:
    user:
      name: ${EUREKA_USER}
      password: ${EUREKA_PASSWORD}

eureka:

  instance:
    hostname: discoveryservice

  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: true