server:
  port: 8762

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

info:
  app:
    name: Grocery Search Service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
