server:
  port: 8764

spring:
  datasource:
    url: ${ORDER_DB_URL}
    username: ${ORDER_DB_USER}
    password: ${ORDER_DB_PASSWORD}

  kafka:
    consumer:
      group-id: order-group

info:
  app:
    name: Order Service
