server:
  port: 8764

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/order_db
    username: postgres
    password: postgres

  kafka:
    consumer:
      group-id: order-group

info:
  app:
    name: Order Service
