spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/payment_db
    username: payment_user
    password: payment_password

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/